### ISSUE TITLE
Set proper experiment directory on your machine

### ISSUE THREAD

**Issue by cheonghm** [QUVA-Lab/COMBO#5]
Hi,
I tried to run COMBO on my machine but get the following error:
`Traceback (most recent call last):
  File "COMBO/main.py", line 253, in <module>
    COMBO(**kwag_)
  File "COMBO/main.py", line 130, in COMBO
    exp_dir = experiment_directory()
  File "/.../COMBO/COMBO/config.py", line 22, in experiment_directory
    raise ValueError('Set proper experiment directory on your machine.')
ValueError: Set proper experiment directory on your machine.`

(Note I'm not using conda because conda install could not retrieve the required libraries) 

How do I set the experiment directory so that I can run COMBO on my own machine?

**Comment by cheonghm** [comment]
Never mind, I modified the config.py code to set a local directory.
